// List of known disposable / temporary email domains
// Source: public disposable email lists, curated for 2025

export const disposableDomains: string[] = [
  "0-mail.com","0815.ru","0clickemail.com","0wnd.net","10minutemail.com","10mail.org","20minutemail.com",
  "2prong.com","30minutemail.com","33mail.com","4warding.com","4warding.net","5ymail.com","60minutemail.com",
  "6ip.us","6mail.ga","6paq.com","7mail.ga","7mail.ml","99experts.com","aaabbbccc.email",
  "abcflashmail.com","abusemail.de","amail.com","anonbox.net","anonmail.top","antichef.com","antichef.net",
  "antispam.de","armail.com","artman-conception.com","armyspy.com","emailtemporanea.com","emailtemporario.com.br",
  "emailtmp.com","emailsensei.com","emailfake.com","emailfake.org","emailgo.de","emailias.com","emailinfive.com",
  "emailmiser.com","emailproxsy.com","emailsensei.com","emailtemporanea.com","emz.net","enterto.com",
  "ephemail.net","explodemail.com","fakeinbox.com","fakeinformation.com","fake-mail.net","fake-mail.com",
  "fakemailgenerator.com","fakemailz.com","fmail.co","fudgerub.com","gishpuppy.com","goemailgo.com",
  "guerrillamail.com","guerrillamail.net","guerrillamail.org","harakirimail.com","hush.ai","hushmail.com",
  "ieatspam.eu","imails.info","inboxbear.com","inboxalias.com","inboxclean.com","inboxclean.org","inboxproxy.com",
  "incognitomail.com","ipoo.org","jetable.com","jetable.net","jetable.org","jourrapide.com","kasmail.com",
  "killmail.com","klassmaster.com","klassmaster.net","klassmaster.org","klzlk.com","lazymail.com","letthemeatspam.com",
  "mail-temporaire.fr","mail.by","mail.mezimages.net","mail.zp.ua","mail1a.de","mail2rss.org","mail333.com",
  "mailcatch.com","maildrop.cc","maileater.com","mailexpire.com","mailfa.tk","mailforspam.com","mailfreeonline.com",
  "mailguard.me","mailin8r.com","mailinator.com","mailinater.com","mailismagic.com","mailme.lv","mailmetrash.com",
  "mailmoat.com","mailnesia.com","mailnull.com","mailsac.com","mailshell.com","mailsiphon.com","mailtemp.info",
  "mailtemp.net","mailtome.de","mailtothis.com","mailzilla.org","meltmail.com","mintemail.com","monemail.fr",
  "mt2016.com","my10minutemail.com","mytrashmail.com","nepwk.com","nobulk.com","nomail.pw","nomail.xl.cx",
  "nomail2me.com","nospam.ze.tc","nospam4.us","nospamfor.us","nospammail.net","notmailinator.com","nowmymail.com",
  "nullbox.info","nurfuerspam.de","oneoffemail.com","onetimeemail.com","opayq.com","ordinaryemail.com","plexolan.de",
  "pookmail.com","privymail.net","proxymail.eu","quickinbox.com","rcpt.at","receiveee.com","receivefreesms.com",
  "recursor.net","recode.me","rppkn.com","safe-mail.net","safetymail.info","safetypost.de","saynotospams.com",
  "selfdestructingmail.com","sendspamhere.com","sharklasers.com","shiftmail.com","skeefmail.com","slopsbox.com",
  "smellfear.com","sneakemail.com","sogetthis.com","spam.la","spam.su","spam4.me","spamail.de","spambog.com",
  "spambog.net","spambog.ru","spambox.info","spambox.us","spamcero.com","spamcowboy.com","spamcowboy.net",
  "spamcowboy.org","spamday.com","spamex.com","spamfree.eu","spamfree24.com","spamfree24.de","spamgourmet.com",
  "spamherelots.com","spamhereplease.com","spamhole.com","spamify.com","spaminator.de","spamkill.info","spaml.com",
  "spammotel.com","spamobox.com","spamoff.de","spamslicer.com","spamspot.com","spamthis.co.uk","spamthisplease.com",
  "spamtrail.com","spamtroll.net","speed.1s.fr","stuffmail.de","temp-mail.org","temp-mail.io","tempa.de",
  "tempr.email","tempemail.co.za","tempemail.com","tempemail.net","tempemail.org","tempinbox.com","tempmail.de",
  "tempmail.eu","tempmail.fr","tempmail.io","tempmail.live","tempmail.net","tempmail.org","tempmail.plus",
  "tempmailaddress.com","tempmailer.com","tempomail.fr","temporaryemail.net","temporaryemail.org",
  "temporaryinbox.com","temporarymailaddress.com","tempymail.com","throwawayemailaddress.com","trash-mail.com",
  "trash-mail.de","trashmail.com","trashmail.de","trashmail.me","trashmail.net","trashmailer.com","trashymail.com",
  "trashymail.net","trashymail.org","trashy-mail.com","trashymail.de","trashmail.ws","trashmail.me",
  "trash-mail.net","trashmailbox.com","trashmailer.de","trashmail.org","trashmail.ws","tmpmail.org","tmail.com",
  "tmailinator.com","toomail.biz","top-mail.com","trbvm.com","trash-mail.de","trashmail.com","trashmail.de",
  "trashmail.me","trashmail.net","trbvm.com","vtagged.com","wegwerfmail.de","wegwerfmail.net","wegwerfmail.org",
  "wegwerfemail.de","wegwerfemail.net","wegwerfemail.org","yopmail.com","yopmail.fr","yopmail.net","yopmail.org"
];
